// Generated by CoffeeScript 1.7.1
(function() {
  var FileData, fs;

  fs = require("fs");

  exports.getdata = function(fileloc, fn, encoding) {
    if (encoding === 'undefined') {
      encoding = 'utf8';
    }
    return fs.readFile(fileloc, encoding, function(err, data) {
      if (!err) {
        return fn(data);
      }
    });
  };

  FileData = function(fileloc, enc) {
    this.fileloc = fileloc;
    if (enc === 'undefined') {
      enc = 'utf8';
    }
    return this.enc = enc;
  };

  FileData.prototype.getData = function(fn) {
    return fs.readFile(this.fileloc, this.enc, function(err, data) {
      return fn(err, data);
    });
  };

  module.exports.FileData = FileData;

}).call(this);
