// Generated by CoffeeScript 1.7.1
(function() {
  var multiparty;

  multiparty = require("multiparty");

  exports.stream_file_upload = function(req, res, next) {
    var form, needed_parts, succeeded_parts;
    form = new multiparty.Form();
    needed_parts = 0;
    succeeded_parts = 0;
    return form.on("part", function(part) {
      var val;
      needed_parts += 1;
      if (part.filename) {
        req.file = part;
        if (needed_parts === (succeeded_parts += 1)) {
          return next();
        }
      } else {
        val = "";
        part.on("data", function(data) {
          return val += data;
        });
        return part.on("end", function() {
          req.body[part.name] = val;
          if (needed_parts === (succeeded_parts += 1)) {
            return next();
          }
        });
      }
    });
  };

}).call(this);
